force-app/main/default/objects/PDF_Data__b/PDF_Data__b.object-meta.xml
<CustomObject>
    <label>PDF_Data</label>
    <pluralLabel>PDF_Data</pluralLabel>
</CustomObject>

force-app/main/default/objects/PDF_Data__b/fields/PDF_Content__c.field-meta.xml
<CustomField>
    <fullName>PDF_Content__c</fullName>
    <description>Content of the pdf</description>
    <label>PDF_Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PDF_Data__b/fields/PDF_Id__c.field-meta.xml
<CustomField>
    <fullName>PDF_Id__c</fullName>
    <label>PDF_Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/pdfPageController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-25-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class pdfPageController {
    public String pdfText{get;set;}
    public pdfPageController() {
        String pdfId = ApexPages.currentPage().getParameters().get('pdfText');
        pdfText = String.escapeSingleQuotes(
            [SELECT PDF_Id__c, PDF_Content__c FROM PDF_Data__b WHERE PDF_Id__c = :pdfId].PDF_Content__c
        );
    }
}