force-app/main/default/objects/PDF_Data__b/PDF_Data__b.object-meta.xml
<CustomObject>
    <label>PDF_Data</label>
    <pluralLabel>PDF_Data</pluralLabel>
</CustomObject>

force-app/main/default/objects/PDF_Data__b/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>Id</description>
    <label>Id</label>
    <length>225</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDF_Data__b/fields/PDF_Content__c.field-meta.xml
<CustomField>
    <fullName>PDF_Content__c</fullName>
    <description>Content of the pdf</description>
    <label>PDF_Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PDF_Data__b/fields/PDF_Id__c.field-meta.xml
<CustomField>
    <fullName>PDF_Id__c</fullName>
    <label>PDF_Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/pdfController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-25-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class pdfController {

    @AuraEnabled
    public static string storeHtmlData(String pdfId, String htmlData){
        List<PDF_Data__b> pdfData = new List<PDF_Data__b>();
        PDF_Data__b content = new PDF_Data__b(PDF_Id__c=pdfId , Id__c='1234567890', PDF_Content__c=htmlData);
        // pdfId => Unique(timeStamp)
        pdfData.add(content);
        Database.insertImmediate(pdfData);
        return pdfId;
    }

    @AuraEnabled
    public static string generatePdf(String pdfId){
        Pagereference page = Page.renderAsPDF;
        page.getParameters().put('pdfText', pdfId);
        List<Skill__c> sk = new List<Skill__c>();
        Skill__c ski = new Skill__c(Skill_Name__c='aa');
        sk.add(ski);
        Database.SaveResult srList = Database.insert(ski,true);
        String aa = srList.getId();
        Skill__c skiv = new Skill__c(Id = aa);
        Attachment objAttachment = new Attachment();
        objAttachment.Name='invoice.pdf';
        objAttachment.ParentId = skiv.Id;
        objAttachment.Body = page.getContentaspdf();
        objAttachment.IsPrivate = false;
        insert objAttachment;
        System.debug(page.getContentaspdf());
        return aa;
    }

    @AuraEnabled
    public static void deleteData(String pdfId){
        List<PDF_Data__b> pdfData = [SELECT PDF_Id__c FROM PDF_Data__b WHERE PDF_Id__c = :pdfId];
        //"Only indexed one needed in select statement[SELECT =>PDF_Id__c FROM PDF_Data__b WHERE PDF_Id__c = :pdfId]"
        database.deleteImmediate(pdfData);
    }

    //      /apex/renderAsPDF?pdfText=1643117439460






    // @AuraEnabled
    // public static String generatePDF(String htmlData){
    //     Pagereference page = Page.renderAsPDF;
    //     page.getParameters().put('pdfText', htmlData);
    //     List<Skill__c> sk = new List<Skill__c>();
    //     Skill__c ski = new Skill__c(Skill_Name__c='aa');
    //     sk.add(ski);
    //     Database.SaveResult srList = Database.insert(ski,true);
    //     String aa = srList.getId();
    //     Skill__c skiv = new Skill__c(Id = aa);
    //     Attachment objAttachment = new Attachment();
    //     objAttachment.Name='invoice.pdf';
    //     objAttachment.ParentId = skiv.Id;
    //     objAttachment.Body = page.getContentaspdf();
    //     objAttachment.IsPrivate = false;
    //     insert objAttachment;
    //     System.debug(page.getContentaspdf());
    //     return aa;
    // }
}